blank_issues_enabled: false
contact_links:
  - name: ðŸ“– DocumentaciÃ³n
    url: https://github.com/Angel-Baez/gondolapp-beta/tree/main/docs
    about: Consulta la documentaciÃ³n del proyecto
  - name: ðŸ’¬ Discusiones
    url: https://github.com/Angel-Baez/gondolapp-beta/discussions
    about: Ãšnete a las discusiones de la comunidad
  - name: ðŸš€ Roadmap
    url: https://github.com/Angel-Baez/gondolapp-beta/projects
    about: Revisa el roadmap del proyecto
